# Generated by Django 5.1.3 on 2024-11-25 03:58

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.channel_picture_path),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(upload_to=content.models.content_file_path),
        ),
    ]
